# Generated by Django 3.2.9 on 2022-01-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCentroSalud', '0003_alter_persona_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='documento',
            field=models.CharField(max_length=15),
        ),
    ]
